### ISSUE TITLE
Need to add EASYOCR_MODULE_PATH to work in read-only containers

### ISSUE THREAD

**Issue by angelnu** [DS4SD/docling-serve#37]
Thanks for this great tool and API!

I was not able to start the container in OpenShift until I added the following env variable `EASYOCR_MODULE_PATH: /tmp`.

As reference: here is the flux helmrelease I used to start the service in OpenShift:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app docling
spec:
  serviceAccountName: ${TECHNICAL_ACCOUNT}
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: ${TENANT_NAMESPACE}
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      app:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              #repository: ghcr.io/ds4sd/docling-serve-cpu
              repository: ghcr.io/ds4sd/docling-serve  # ca 3 times faster 
              tag: main #v0.1.0 <- not ready for OpenShift so use main
            env:
              PORT: &port 5001
              UVICORN_WORKERS: 1
              WITH_UI: True # The Gradio UI will be available at /ui
              RELOAD: False
              EASYOCR_MODULE_PATH: /tmp
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 2
                memory: 2Gi
                nvidia.com/gpu: 1
              limits:
                cpu: 4
                memory: 4Gi
                nvidia.com/gpu: 1
    defaultPodOptions:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    service:
      app:
        controller: app
        ports:
          http:
            port: *port
    ingress:
      app:
        className: external
        hosts:
          - host: "{{ .Release.Name }}-${TENANT_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
```
